// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.2
// source: model_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatCompletionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatSessionId string   `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`
	InputIds      []uint32 `protobuf:"varint,2,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`
	AttentionMask []uint32 `protobuf:"varint,3,rep,packed,name=attention_mask,json=attentionMask,proto3" json:"attention_mask,omitempty"`
}

func (x *ChatCompletionReq) Reset() {
	*x = ChatCompletionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionReq) ProtoMessage() {}

func (x *ChatCompletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_model_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionReq.ProtoReflect.Descriptor instead.
func (*ChatCompletionReq) Descriptor() ([]byte, []int) {
	return file_model_server_proto_rawDescGZIP(), []int{0}
}

func (x *ChatCompletionReq) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *ChatCompletionReq) GetInputIds() []uint32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *ChatCompletionReq) GetAttentionMask() []uint32 {
	if x != nil {
		return x.AttentionMask
	}
	return nil
}

type ChatCompletionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer   string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	TokenCnt uint32 `protobuf:"varint,2,opt,name=token_cnt,json=tokenCnt,proto3" json:"token_cnt,omitempty"`
}

func (x *ChatCompletionResult) Reset() {
	*x = ChatCompletionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResult) ProtoMessage() {}

func (x *ChatCompletionResult) ProtoReflect() protoreflect.Message {
	mi := &file_model_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResult.ProtoReflect.Descriptor instead.
func (*ChatCompletionResult) Descriptor() ([]byte, []int) {
	return file_model_server_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletionResult) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ChatCompletionResult) GetTokenCnt() uint32 {
	if x != nil {
		return x.TokenCnt
	}
	return 0
}

var File_model_server_proto protoreflect.FileDescriptor

var file_model_server_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0x7f, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x61, 0x74, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x61, 0x73, 0x6b, 0x22, 0x4b, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6e, 0x74,
	0x32, 0x6d, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_server_proto_rawDescOnce sync.Once
	file_model_server_proto_rawDescData = file_model_server_proto_rawDesc
)

func file_model_server_proto_rawDescGZIP() []byte {
	file_model_server_proto_rawDescOnce.Do(func() {
		file_model_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_server_proto_rawDescData)
	})
	return file_model_server_proto_rawDescData
}

var file_model_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_server_proto_goTypes = []interface{}{
	(*ChatCompletionReq)(nil),    // 0: model_server.ChatCompletionReq
	(*ChatCompletionResult)(nil), // 1: model_server.ChatCompletionResult
}
var file_model_server_proto_depIdxs = []int32{
	0, // 0: model_server.ModelServerService.ChatCompletion:input_type -> model_server.ChatCompletionReq
	1, // 1: model_server.ModelServerService.ChatCompletion:output_type -> model_server.ChatCompletionResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_server_proto_init() }
func file_model_server_proto_init() {
	if File_model_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_server_proto_goTypes,
		DependencyIndexes: file_model_server_proto_depIdxs,
		MessageInfos:      file_model_server_proto_msgTypes,
	}.Build()
	File_model_server_proto = out.File
	file_model_server_proto_rawDesc = nil
	file_model_server_proto_goTypes = nil
	file_model_server_proto_depIdxs = nil
}
