// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.2
// source: tokenizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenizerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentMessageId string `protobuf:"bytes,1,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Prompt          string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *TokenizerReq) Reset() {
	*x = TokenizerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenizerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizerReq) ProtoMessage() {}

func (x *TokenizerReq) ProtoReflect() protoreflect.Message {
	mi := &file_tokenizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizerReq.ProtoReflect.Descriptor instead.
func (*TokenizerReq) Descriptor() ([]byte, []int) {
	return file_tokenizer_proto_rawDescGZIP(), []int{0}
}

func (x *TokenizerReq) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *TokenizerReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TokenizerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputIds         []uint32 `protobuf:"varint,1,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`
	AttentionMask    []uint32 `protobuf:"varint,2,rep,packed,name=attention_mask,json=attentionMask,proto3" json:"attention_mask,omitempty"`
	CurrentTokensCnt uint32   `protobuf:"varint,3,opt,name=current_tokens_cnt,json=currentTokensCnt,proto3" json:"current_tokens_cnt,omitempty"`
}

func (x *TokenizerResp) Reset() {
	*x = TokenizerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenizerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizerResp) ProtoMessage() {}

func (x *TokenizerResp) ProtoReflect() protoreflect.Message {
	mi := &file_tokenizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizerResp.ProtoReflect.Descriptor instead.
func (*TokenizerResp) Descriptor() ([]byte, []int) {
	return file_tokenizer_proto_rawDescGZIP(), []int{1}
}

func (x *TokenizerResp) GetInputIds() []uint32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *TokenizerResp) GetAttentionMask() []uint32 {
	if x != nil {
		return x.AttentionMask
	}
	return nil
}

func (x *TokenizerResp) GetCurrentTokensCnt() uint32 {
	if x != nil {
		return x.CurrentTokensCnt
	}
	return 0
}

var File_tokenizer_proto protoreflect.FileDescriptor

var file_tokenizer_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x0c,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x11,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x22, 0x81, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x43, 0x6e, 0x74, 0x32, 0x52, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65,
	0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokenizer_proto_rawDescOnce sync.Once
	file_tokenizer_proto_rawDescData = file_tokenizer_proto_rawDesc
)

func file_tokenizer_proto_rawDescGZIP() []byte {
	file_tokenizer_proto_rawDescOnce.Do(func() {
		file_tokenizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenizer_proto_rawDescData)
	})
	return file_tokenizer_proto_rawDescData
}

var file_tokenizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tokenizer_proto_goTypes = []interface{}{
	(*TokenizerReq)(nil),  // 0: tokenizer.TokenizerReq
	(*TokenizerResp)(nil), // 1: tokenizer.TokenizerResp
}
var file_tokenizer_proto_depIdxs = []int32{
	0, // 0: tokenizer.TokenizerService.Tokenizer:input_type -> tokenizer.TokenizerReq
	1, // 1: tokenizer.TokenizerService.Tokenizer:output_type -> tokenizer.TokenizerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokenizer_proto_init() }
func file_tokenizer_proto_init() {
	if File_tokenizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenizerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenizerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenizer_proto_goTypes,
		DependencyIndexes: file_tokenizer_proto_depIdxs,
		MessageInfos:      file_tokenizer_proto_msgTypes,
	}.Build()
	File_tokenizer_proto = out.File
	file_tokenizer_proto_rawDesc = nil
	file_tokenizer_proto_goTypes = nil
	file_tokenizer_proto_depIdxs = nil
}
