# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tokenizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenizer.proto\x12\ttokenizer\"9\n\x0cTokenizerReq\x12\x19\n\x11parent_message_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"V\n\rTokenizerResp\x12\x11\n\tinput_ids\x18\x01 \x03(\r\x12\x16\n\x0e\x61ttention_mask\x18\x02 \x03(\r\x12\x1a\n\x12\x63urrent_tokens_cnt\x18\x03 \x01(\r2R\n\x10TokenizerService\x12>\n\tTokenizer\x12\x17.tokenizer.TokenizerReq\x1a\x18.tokenizer.TokenizerRespB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TOKENIZERREQ']._serialized_start=30
  _globals['_TOKENIZERREQ']._serialized_end=87
  _globals['_TOKENIZERRESP']._serialized_start=89
  _globals['_TOKENIZERRESP']._serialized_end=175
  _globals['_TOKENIZERSERVICE']._serialized_start=177
  _globals['_TOKENIZERSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
