# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tokenizer_pb2 as tokenizer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tokenizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TokenizerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenizer = channel.unary_unary(
                '/tokenizer.TokenizerService/Tokenizer',
                request_serializer=tokenizer__pb2.TokenizerReq.SerializeToString,
                response_deserializer=tokenizer__pb2.TokenizerResp.FromString,
                _registered_method=True)
        self.DeTokenizer = channel.unary_unary(
                '/tokenizer.TokenizerService/DeTokenizer',
                request_serializer=tokenizer__pb2.DeTokenizerReq.SerializeToString,
                response_deserializer=tokenizer__pb2.DeTokenizerResult.FromString,
                _registered_method=True)


class TokenizerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tokenizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeTokenizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenizer': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenizer,
                    request_deserializer=tokenizer__pb2.TokenizerReq.FromString,
                    response_serializer=tokenizer__pb2.TokenizerResp.SerializeToString,
            ),
            'DeTokenizer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeTokenizer,
                    request_deserializer=tokenizer__pb2.DeTokenizerReq.FromString,
                    response_serializer=tokenizer__pb2.DeTokenizerResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tokenizer.TokenizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tokenizer.TokenizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TokenizerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tokenizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenizer.TokenizerService/Tokenizer',
            tokenizer__pb2.TokenizerReq.SerializeToString,
            tokenizer__pb2.TokenizerResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeTokenizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenizer.TokenizerService/DeTokenizer',
            tokenizer__pb2.DeTokenizerReq.SerializeToString,
            tokenizer__pb2.DeTokenizerResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
