// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: model_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelServerService_ChatCompletion_FullMethodName = "/model_server.ModelServerService/ChatCompletion"
)

// ModelServerServiceClient is the client API for ModelServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelServerServiceClient interface {
	ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResult], error)
}

type modelServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServerServiceClient(cc grpc.ClientConnInterface) ModelServerServiceClient {
	return &modelServerServiceClient{cc}
}

func (c *modelServerServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelServerService_ServiceDesc.Streams[0], ModelServerService_ChatCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionReq, ChatCompletionResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelServerService_ChatCompletionClient = grpc.ServerStreamingClient[ChatCompletionResult]

// ModelServerServiceServer is the server API for ModelServerService service.
// All implementations must embed UnimplementedModelServerServiceServer
// for forward compatibility.
type ModelServerServiceServer interface {
	ChatCompletion(*ChatCompletionReq, grpc.ServerStreamingServer[ChatCompletionResult]) error
	mustEmbedUnimplementedModelServerServiceServer()
}

// UnimplementedModelServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServerServiceServer struct{}

func (UnimplementedModelServerServiceServer) ChatCompletion(*ChatCompletionReq, grpc.ServerStreamingServer[ChatCompletionResult]) error {
	return status.Errorf(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedModelServerServiceServer) mustEmbedUnimplementedModelServerServiceServer() {}
func (UnimplementedModelServerServiceServer) testEmbeddedByValue()                            {}

// UnsafeModelServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServerServiceServer will
// result in compilation errors.
type UnsafeModelServerServiceServer interface {
	mustEmbedUnimplementedModelServerServiceServer()
}

func RegisterModelServerServiceServer(s grpc.ServiceRegistrar, srv ModelServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedModelServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelServerService_ServiceDesc, srv)
}

func _ModelServerService_ChatCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelServerServiceServer).ChatCompletion(m, &grpc.GenericServerStream[ChatCompletionReq, ChatCompletionResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelServerService_ChatCompletionServer = grpc.ServerStreamingServer[ChatCompletionResult]

// ModelServerService_ServiceDesc is the grpc.ServiceDesc for ModelServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model_server.ModelServerService",
	HandlerType: (*ModelServerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletion",
			Handler:       _ModelServerService_ChatCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "model_server.proto",
}
